services:

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - internal

  mqtt:
    image: eclipse-mosquitto:2
    restart: always
    volumes:
      - mqtt_config:/mosquitto/config
      - mqtt_data:/mosquitto/data
      - mqtt_logs:/mosquitto/log
    ports:
      - "${MQTT_PORT}:1883"
    networks:
      - internal

  api:
    image: localhost:5000/webapi:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
      mqtt:
        condition: service_started
    environment:
      DB_URL: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
    ports:
      - "${API_PORT}:8080"
    networks:
      - internal
      - external

  ui:
    image: localhost:5000/ui:latest
    restart: always
    depends_on:
      - api
    environment:
      VITE_API_URL: 17692290-9ebe-4131-af09-5dcd5616c91d
      VITE_ENV_TEXT: 01b86e83-6e27-4659-978f-243f3d599f1b
      VITE_ENV_COLOR: 2357a9e2-338f-4da3-9e07-0c444f1b7bea
      API_URL: http://localhost:${API_PORT}
    ports:
      - "${UI_PORT}:8080"
    networks:
      - external

volumes:
  db_data:
  mqtt_config:
  mqtt_data:
  mqtt_logs:

networks:
  internal:
    driver: bridge
  external:
    driver: bridge